### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by eliasoberholtz** [sam-astro/Robinhood-Trading-Bot#1]
It doesn't work:

https://user-images.githubusercontent.com/101438328/171438905-0712a39e-9181-4dcf-9960-872f57eee1c3.mp4

**Comment by sam-astro** [comment]
Make sure you have the `robin-stocks` package installed along with the other packages using `pip`, and you change the credentials to your own Robinhood account inside of the python file. This is the api I used, and you may find some of what you need at it's docs: [https://robin-stocks.readthedocs.io/en/latest/]( https://robin-stocks.readthedocs.io/en/latest/)
